/**
 * Handoff Converters — tokens → framework configs (결정론적)
 *
 * LLM 이 생성한 4 token layer 를 받아 프레임워크별 설정 파일/객체를 생성.
 * LLM 이 코드를 직접 작성하지 않으므로 형식 안정성 보장 (문법 오류 0).
 *
 * 산출물:
 *  - DTCG (W3C Design Tokens Community Group) JSON
 *  - Tailwind config (tailwind.config.js 텍스트)
 *  - MUI theme (createTheme 인자 객체 텍스트)
 *  - CSS Variables (:root { --token: value })
 *  - .cursorrules (AI 코딩 도구용 컨텍스트)
 */

const onlyEnabled = (tokens = []) => tokens.filter((t) => t.isEnabled !== false);
const safeId = (id) => String(id || '').toLowerCase().replace(/[^a-z0-9-]/g, '-').replace(/-+/g, '-');

/* ============================================
 * DTCG JSON
 * ============================================ */

export function buildDtcgTokens({ color = [], typography = [], layout = [], gradient = [] } = {}) {
  const dtcg = {
    $schema: 'https://design-tokens.github.io/community-group/format/',
    color: {},
    font: {},
    space: {},
    radius: {},
    grid: {},
    gradient: {},
  };

  for (const c of onlyEnabled(color)) {
    dtcg.color[safeId(c.id || c.label)] = {
      $value: c.hex,
      $type: 'color',
      $description: `${c.label || ''}${c.role ? ` (${c.role})` : ''}`,
    };
  }

  for (const t of onlyEnabled(typography)) {
    dtcg.font[safeId(t.id || t.variant || t.label)] = {
      $value: {
        fontFamily: t.fontFamily,
        fontWeight: t.fontWeight,
        fontSize: t.fontSize,
        lineHeight: t.lineHeight,
        letterSpacing: t.letterSpacing || '0',
      },
      $type: 'typography',
      $description: t.label || '',
    };
  }

  for (const l of onlyEnabled(layout)) {
    const id = safeId(l.id || l.label);
    if (l.kind === 'grid') {
      dtcg.grid[id] = {
        $value: { columns: l.columns, gap: `${l.gap}px` },
        $type: 'grid',
        $description: l.label || '',
      };
    } else if (l.kind === 'spacing') {
      dtcg.space[id] = { $value: `${l.px}px`, $type: 'dimension', $description: l.label || '' };
    } else if (l.kind === 'container') {
      dtcg.space[`${id}-max`] = { $value: l.maxWidth, $type: 'dimension', $description: l.label || '' };
    }
  }

  for (const g of onlyEnabled(gradient)) {
    dtcg.gradient[safeId(g.id || g.label)] = {
      $value: g.gradient,
      $type: 'gradient',
      $description: g.label || '',
    };
  }

  return dtcg;
}

/* ============================================
 * Tailwind config
 * ============================================ */

export function buildTailwindConfig({ color = [], typography = [], layout = [], gradient = [] } = {}) {
  const colors = {};
  for (const c of onlyEnabled(color)) {
    const key = c.role && c.role !== 'neutral' ? c.role : safeId(c.id || c.label);
    if (c.role === 'primary' || c.role === 'secondary' || c.role === 'accent') {
      colors[c.role] = c.hex;
    } else {
      colors[key] = c.hex;
    }
  }

  const fontFamily = {};
  const fontSize = {};
  for (const t of onlyEnabled(typography)) {
    const key = (t.variant || t.id || t.label || 'base').toLowerCase().replace(/[^a-z0-9]/g, '');
    if (t.fontFamily) {
      fontFamily[key] = t.fontFamily.split(',').map((f) => f.trim().replace(/^['"]|['"]$/g, ''));
    }
    if (t.fontSize) {
      fontSize[key] = [t.fontSize, { lineHeight: String(t.lineHeight || 1.5), letterSpacing: t.letterSpacing || '0' }];
    }
  }

  const spacing = {};
  let gridCols = 12;
  let gridGap = 24;
  let containerMaxW = '1200px';
  for (const l of onlyEnabled(layout)) {
    if (l.kind === 'grid') {
      gridCols = l.columns || gridCols;
      gridGap = l.gap || gridGap;
    } else if (l.kind === 'spacing') {
      spacing[safeId(l.id || l.label)] = `${l.px}px`;
    } else if (l.kind === 'container') {
      containerMaxW = l.maxWidth || containerMaxW;
    }
  }

  const backgroundImage = {};
  for (const g of onlyEnabled(gradient)) {
    backgroundImage[safeId(g.id || g.label)] = g.gradient;
  }

  const obj = {
    theme: {
      extend: {
        colors,
        fontFamily,
        fontSize,
        spacing,
        gridTemplateColumns: { main: `repeat(${gridCols}, minmax(0, 1fr))` },
        gap: { main: `${gridGap}px` },
        maxWidth: { container: containerMaxW },
        backgroundImage,
      },
    },
  };

  return `// tailwind.config.js — generated by MUSE\n/** @type {import('tailwindcss').Config} */\nmodule.exports = ${JSON.stringify(obj, null, 2)};\n`;
}

/* ============================================
 * MUI theme
 * ============================================ */

export function buildMuiTheme({ color = [], typography = [], layout = [], gradient = [] } = {}) {
  const palette = { mode: 'light' };
  for (const c of onlyEnabled(color)) {
    if (c.role === 'primary') palette.primary = { main: c.hex };
    else if (c.role === 'secondary') palette.secondary = { main: c.hex };
    else if (c.role === 'accent') palette.warning = { main: c.hex };
  }
  // background = 가장 밝은 neutral 추정
  const surfaces = onlyEnabled(color).filter((c) => c.role === 'neutral' || c.group === 'Surface');
  if (surfaces.length) {
    const lightest = surfaces.reduce((a, b) => (luminance(a.hex) > luminance(b.hex) ? a : b));
    palette.background = { default: lightest.hex, paper: lightest.hex };
  }

  const muiTypography = {};
  for (const t of onlyEnabled(typography)) {
    const variant = t.variant || mapHierarchyToVariant(t);
    muiTypography[variant] = {
      fontFamily: t.fontFamily,
      fontWeight: t.fontWeight,
      fontSize: t.fontSize,
      lineHeight: t.lineHeight,
      letterSpacing: t.letterSpacing || '0',
    };
  }
  const baseFontFamily = onlyEnabled(typography)[0]?.fontFamily;
  if (baseFontFamily) muiTypography.fontFamily = baseFontFamily;

  // shape.borderRadius / spacing 은 layout 토큰에서 추정 (기본값 사용)
  const shape = { borderRadius: 8 };
  const spacing = 8;

  const gradients = {};
  for (const g of onlyEnabled(gradient)) gradients[safeId(g.id || g.label)] = g.gradient;

  const obj = { palette, typography: muiTypography, shape, spacing, gradients };

  return `// mui-theme.js — generated by MUSE\nimport { createTheme } from '@mui/material/styles';\n\nexport const theme = createTheme(${JSON.stringify(obj, null, 2)});\n\nexport default theme;\n`;
}

const mapHierarchyToVariant = (t) => {
  const h = t.hierarchy || (t.fontSize?.includes('rem') && parseFloat(t.fontSize) >= 2 ? 'display' : 'body');
  if (h === 'display') return 'h1';
  if (h === 'heading') return 'h2';
  if (h === 'caption') return 'caption';
  return 'body1';
};

const luminance = (hex) => {
  const m = String(hex || '').match(/^#([0-9a-f]{6})$/i);
  if (!m) return 0;
  const n = parseInt(m[1], 16);
  const r = (n >> 16) & 0xff, g = (n >> 8) & 0xff, b = n & 0xff;
  return 0.299 * r + 0.587 * g + 0.114 * b;
};

/* ============================================
 * CSS Variables
 * ============================================ */

export function buildCssVariables({ color = [], typography = [], layout = [], gradient = [] } = {}) {
  const lines = [':root {'];
  for (const c of onlyEnabled(color)) {
    lines.push(`  --color-${safeId(c.id || c.role || c.label)}: ${c.hex};`);
  }
  for (const t of onlyEnabled(typography)) {
    const id = safeId(t.id || t.variant || t.label);
    lines.push(`  --font-${id}-family: ${t.fontFamily};`);
    lines.push(`  --font-${id}-size: ${t.fontSize};`);
    lines.push(`  --font-${id}-weight: ${t.fontWeight};`);
    lines.push(`  --font-${id}-line-height: ${t.lineHeight};`);
  }
  for (const l of onlyEnabled(layout)) {
    const id = safeId(l.id || l.label);
    if (l.kind === 'grid') {
      lines.push(`  --grid-${id}-columns: ${l.columns};`);
      lines.push(`  --grid-${id}-gap: ${l.gap}px;`);
    } else if (l.kind === 'spacing') {
      lines.push(`  --space-${id}: ${l.px}px;`);
    } else if (l.kind === 'container') {
      lines.push(`  --container-${id}-max: ${l.maxWidth};`);
    }
  }
  for (const g of onlyEnabled(gradient)) {
    lines.push(`  --gradient-${safeId(g.id || g.label)}: ${g.gradient};`);
  }
  lines.push('}');
  return `/* tokens.css — generated by MUSE */\n${lines.join('\n')}\n`;
}

/* ============================================
 * .cursorrules (AI 코딩 도구 컨텍스트)
 * ============================================ */

export function buildCursorRules({ project, tokens, layerDetails }) {
  const c = onlyEnabled(tokens?.color || []);
  const primary = c.find((x) => x.role === 'primary')?.hex;
  const surface = c.find((x) => x.group === 'Surface' || x.role === 'neutral')?.hex;
  const palette = c.map((x) => `  - ${x.label || x.id}: ${x.hex} (${x.role || x.group || 'neutral'})`).join('\n');

  const t = onlyEnabled(tokens?.typography || []);
  const fonts = t.map((x) => `  - ${x.variant || x.id}: ${x.fontFamily} ${x.fontWeight} ${x.fontSize}`).join('\n');

  return `# .cursorrules — ${project?.name || 'MUSE'}

> Generated by MUSE on ${new Date().toISOString().slice(0, 10)} (mode: handoff)

## Project Intent
${project?.intent || '(없음)'}

## Design Tokens (source of truth)

### Colors
${palette}
- Primary: ${primary || '(미지정)'}
- Surface: ${surface || '(미지정)'}

### Typography
${fonts}

## Implementation Rules
1. ALL color values MUST come from \`tokens.dtcg.json\` or the framework config (Tailwind / MUI / CSS vars). Never hard-code HEX.
2. Use semantic role names (primary / secondary / accent) when consuming colors.
3. Typography variants follow the generated config — do not invent new sizes.
4. Layout grid: use the generated grid template / gap. Do not bypass with arbitrary CSS.
5. When a component needs a token not in the config, ADD it to the source tokens first.

## Layer Application Notes
${layerDetails ? Object.entries(layerDetails).map(([k, v]) => `### ${k}\n${v}`).join('\n\n') : '(layerDetails 없음)'}

## Files In This Bundle
- \`tokens.dtcg.json\` — DTCG standard tokens (machine-readable source of truth)
- \`frameworks/tailwind.config.js\` — Tailwind 변환
- \`frameworks/mui-theme.js\` — MUI v7 theme
- \`frameworks/tokens.css\` — 순수 CSS variables
- \`DESIGN_SYSTEM.md\` — 5 layer 한글 상세 (사람용)
- \`README.md\` — 사용 가이드
`;
}

/* ============================================
 * DESIGN_SYSTEM.md (5 layer 상세 문서)
 * ============================================ */

export function buildDesignSystemMd({ project, tokens, visualDirection, layerDetails }) {
  const date = new Date().toISOString().slice(0, 10);
  const ld = layerDetails || {};
  const vd = visualDirection || { markdown: '', tags: {} };

  return `# ${project?.name || 'Design System'}

_Generated by MUSE on ${date} — mode: handoff_

**Intent**: ${project?.intent || '(없음)'}

---

## 0. Visual Direction

${vd.markdown || '(없음)'}

${vd.tags && Object.keys(vd.tags).length ? `**Tags**: ${Object.entries(vd.tags).map(([k, v]) => `${k}: ${(v || []).join(', ')}`).join(' · ')}` : ''}

---

## 1. Color Layer

${ld.color || '(상세 없음)'}

**토큰 ${(tokens?.color || []).length}개** — \`tokens.dtcg.json\` 의 \`color.*\` 참조

---

## 2. Typography Layer

${ld.typography || '(상세 없음)'}

**토큰 ${(tokens?.typography || []).length}개** — \`tokens.dtcg.json\` 의 \`font.*\` 참조

---

## 3. Layout Layer

${ld.layout || '(상세 없음)'}

**토큰 ${(tokens?.layout || []).length}개** — \`tokens.dtcg.json\` 의 \`grid.*\` / \`space.*\` 참조

---

## 4. Gradient Layer

${ld.gradient || '(상세 없음)'}

**토큰 ${(tokens?.gradient || []).length}개** — \`tokens.dtcg.json\` 의 \`gradient.*\` 참조

---

## 5. Visual Direction Layer

${ld.visualDirection || '(상세 없음)'}

---

## 프레임워크 전환 가이드

### Tailwind
\`frameworks/tailwind.config.js\` 를 프로젝트 루트에 복사. \`module.exports.theme.extend\` 가 토큰을 노출.

### MUI v7
\`frameworks/mui-theme.js\` import 후 \`<ThemeProvider theme={theme}>\` 로 감싸기.

### Pure CSS
\`frameworks/tokens.css\` 를 entry 에 import. \`var(--color-primary)\` 등으로 사용.

### AI 코딩 도구 (Cursor / Claude Code)
프로젝트 루트에 \`.cursorrules\` 복사. 도구가 토큰을 컨텍스트로 인지함.
`;
}
