/**
 * MUSE Export — Universal JSON + ZIP 번들 생성
 *
 * 출력 스키마는 MUI 특화가 아닌 "임의 프레임워크에서 소비 가능한 형태".
 * 외부 AI 코딩 도구(Cursor/Claude Code 등)가 그대로 context로 받을 수 있게 설계.
 *
 * ZIP 구조:
 *   muse-export-{slug}.zip
 *   ├── muse.json                 ← universal tokens + metadata + vd 태그
 *   ├── visual-direction.md       ← 독립 MD (muse.json.visualDirection.markdown과 동일)
 *   ├── README.md                 ← AI 도구용 사용 가이드
 *   └── references/
 *       ├── ref-XXX.jpg
 *       └── ...
 */

import JSZip from 'jszip';
import {
  buildDtcgTokens,
  buildTailwindConfig,
  buildMuiTheme,
  buildCssVariables,
  buildCursorRules,
  buildDesignSystemMd,
  buildAiPasteBlock,
  buildAttachmentTable,
  inferImageExt,
} from './handoffConverters';

const MUSE_EXPORT_VERSION = '1.0';

/* ============================================
 * Helpers
 * ============================================ */

const slugify = (name) =>
  (name || 'muse')
    .toLowerCase()
    .trim()
    .replace(/[^\w\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-') || 'muse';

const inferExt = (url, mime) => {
  if (typeof url === 'string' && url.startsWith('data:')) {
    const m = url.match(/^data:image\/([^;]+)/);
    if (m) return `.${m[1] === 'jpeg' ? 'jpg' : m[1]}`;
  }
  if (mime) {
    if (mime.includes('jpeg') || mime.includes('jpg')) return '.jpg';
    if (mime.includes('png')) return '.png';
    if (mime.includes('webp')) return '.webp';
    if (mime.includes('gif')) return '.gif';
    if (mime.includes('svg')) return '.svg';
  }
  const last = (typeof url === 'string' ? url : '').split('/').pop()?.split('?')[0] || '';
  const em = last.match(/\.([a-zA-Z0-9]+)$/);
  if (em) {
    const ext = em[1].toLowerCase();
    return ext === 'jpeg' ? '.jpg' : `.${ext}`;
  }
  return '.jpg';
};

/** 활성 토큰만 뽑아 export용 형태로 변환 (내부 _flag는 제외) */
const pickEnabledTokens = (list) =>
  (list || [])
    .filter((t) => t.isEnabled !== false)
    .map((t) => {
      const { isEnabled: _e, _removed, _pending, _tagError, ...rest } = t;
      return rest;
    });

/* ============================================
 * Universal JSON builder
 * ============================================ */

/**
 * 프로젝트 + 분석 + 참조된 references → 범용 JSON 스키마로 변환.
 *
 * 특징:
 *  - MUI · Tailwind · 어떤 프레임워크에도 종속되지 않음
 *  - color.hex, typography.fontSize (CSS value), layout.kind 등 값 그대로 명시
 *  - visualDirection.markdown 이 서술형 디렉션 포함 (한글)
 *  - references 는 파일 경로만 포함 (이미지 바이너리는 별도 ZIP 엔트리)
 */
export function buildUniversalJson({ project, analysis, references }) {
  const projectRefs = (references || []).filter((r) =>
    (project.referenceIds || []).includes(r.id),
  );

  const refFileMap = {};
  projectRefs.forEach((r, i) => {
    const prefix = String(i + 1).padStart(2, '0');
    refFileMap[r.id] = `${prefix}-${r.id}${inferImageExt(r.thumbnailUrl)}`;
  });

  return {
    meta: {
      museVersion: MUSE_EXPORT_VERSION,
      project: {
        id: project.id,
        name: project.name,
        intent: project.intent,
        mode: project.mode,
        createdAt: project.createdAt,
      },
      generatedAt: new Date().toISOString(),
      referenceCount: projectRefs.length,
    },

    color: {
      description: '이미지 기반으로 추출한 컬러 토큰. HEX 값 그대로 사용 가능. role은 primary/secondary/accent/neutral.',
      tokens: pickEnabledTokens(analysis?.color),
    },

    typography: {
      description: '타이포그래피 토큰. fontFamily는 CSS font stack, fontSize는 clamp() 등 CSS 값 그대로.',
      tokens: pickEnabledTokens(analysis?.typography),
    },

    layout: {
      description: '레이아웃 토큰. kind는 grid(columns+gap) / spacing(px) / container(ratio+maxWidth).',
      tokens: pickEnabledTokens(analysis?.layout),
    },

    gradient: {
      description: '그라디언트 토큰. gradient 필드에 CSS gradient 문자열 그대로 적용 가능.',
      tokens: pickEnabledTokens(analysis?.gradient),
    },

    visualDirection: {
      description: '맥락 기반 비주얼 디렉션. 서술형 MD 문서 + 집계 태그.',
      markdown: analysis?.visualDirection?.markdown || '',
      tags: analysis?.visualDirection?.tags || { genre: [], style: [], subject: [] },
    },

    references: projectRefs.map((r) => ({
      id: r.id,
      filename: refFileMap[r.id],
      title: r.title,
      tags: r.tags,
      dominantColors: r.dominantColors,
      source: r.source,
    })),
  };
}

/* ============================================
 * README 빌더 (AI 도구 가이드)
 * ============================================ */

function buildReadme(project, references) {
  const name = project.name || 'Untitled';
  const attachmentTable = buildAttachmentTable(project, references);
  return `# MUSE Export — ${name}

Generated by MUSE on ${new Date().toISOString().slice(0, 10)}.

## Reference Images (외부 AI 에 첨부할 정확한 파일명)

${attachmentTable}

> 외부 AI 에 첨부할 때 위 파일명을 그대로 사용. 본문의 \`ref-XXX\` 언급은 위 파일과 1:1 매칭됩니다.

## 파일 구성

| 파일 | 용도 |
|------|------|
| \`muse.json\` | 범용 디자인 토큰 + 메타 + 비주얼 디렉션 태그 (기계 판독용) |
| \`visual-direction.md\` | 서술형 디자인 디렉션 (사람/LLM 판독용) |
| \`ai-paste-block.md\` | 외부 AI 도구 paste 용 (플랫폼 중립 prose + 첨부물 매칭) |
| 각 reference 이미지 | 위 매칭 표 참조 |

## AI 코딩 도구에 넣는 법

### Cursor / Claude Code
이 폴더를 프로젝트 루트 (예: \`design/muse/\`)에 복사한 뒤 프롬프트:

> \`design/muse/muse.json\`의 토큰을 사용해 이 프로젝트를 구현하라.
> 톤과 의도는 \`design/muse/visual-direction.md\`를 따른다.
> 필요 시 위 매칭 표의 원본 이미지를 참고한다.

### ChatGPT / Claude 대화
\`ai-paste-block.md\` 본문을 paste + 매칭 표의 이미지 파일을 첨부 순번대로 업로드:

> 이 토큰과 디렉션 문서를 기준으로 {프레임워크} 컴포넌트를 만들어줘.

## muse.json 스키마 요약

- \`meta\` — 프로젝트 메타 (name/intent/mode/createdAt)
- \`color.tokens\` — \`[{ id, label, hex, role, group, emphasis }]\`
- \`typography.tokens\` — \`[{ id, label, variant, fontFamily, fontWeight, fontSize, lineHeight, letterSpacing }]\`
- \`layout.tokens\` — \`[{ id, label, kind, columns|gap|px|ratio|maxWidth }]\`
- \`gradient.tokens\` — \`[{ id, label, gradient }]\` (CSS string)
- \`visualDirection\` — \`{ markdown, tags: { genre, style, subject } }\`
- \`references\` — \`[{ id, filename, title, tags, dominantColors }]\`

프레임워크 비종속: MUI/Tailwind/Chakra/Styled Components 어디서든 \`hex\` · CSS value를 그대로 쓰면 됨.

---

**의도**: ${project.intent || '(없음)'}
**프로젝트 모드**: ${project.mode || 'system'}
`;
}

/* ============================================
 * ZIP builder + download
 * ============================================ */

/**
 * concept 모드 전용 — 단일 .md 파일 다운로드 (ZIP 없음)
 * @returns {Promise<{ filename: string, size: number }>}
 */
export async function exportConceptPrompt({ project, analysis, references }) {
  const zip = new JSZip();
  const promptText = analysis?.conceptPrompt || '';
  const slug = slugify(project?.name);
  const date = new Date().toISOString().slice(0, 10);
  const pasteBlock = buildAiPasteBlock({ project, analysis, references });
  const attachmentTable = buildAttachmentTable(project, references);

  const md = `# ${project?.name || 'Concept'} — Concept Prompt

_Generated by MUSE on ${date} (mode: concept)_

## Reference Images (외부 AI 에 첨부할 정확한 파일명)

${attachmentTable}

> 외부 AI 도구에 paste 할 때 위 파일명을 그대로 첨부 순번대로 업로드.

## 사용 방법

아래 "AI Paste Block" 단락을 외부 AI 도구 (Claude Design / Gemini / AI Studio / ChatGPT 등) 에
그대로 붙여넣고 위 매칭 표의 파일을 첨부 순번대로 함께 업로드하세요.

## Prompt (raw)

${promptText}

---

${pasteBlock}

---

**프로젝트 의도**: ${project?.intent || '(없음)'}
`;
  zip.file('concept-prompt.md', md);
  zip.file('ai-paste-block.md', pasteBlock);

  // 이미지 동봉 (첨부 순번 prefix, paste block 매칭 단서와 일치)
  const projectRefs = (project?.referenceIds || [])
    .map((id) => (references || []).find((r) => r.id === id))
    .filter(Boolean);
  await Promise.all(projectRefs.map(async (ref, i) => {
    const prefix = String(i + 1).padStart(2, '0');
    const filename = `${prefix}-${ref.id}${inferImageExt(ref.thumbnailUrl)}`;
    try {
      const res = await fetch(ref.thumbnailUrl);
      if (!res.ok) throw new Error(`status ${res.status}`);
      const blob = await res.blob();
      zip.file(filename, blob);
    } catch (e) {
      zip.file(`${prefix}-${ref.id}.error.txt`, `Failed to include image: ${e?.message || String(e)}`);
    }
  }));

  const zipBlob = await zip.generateAsync({ type: 'blob' });
  const filename = `muse-${slug}-concept-${date}.zip`;
  const url = URL.createObjectURL(zipBlob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
  return { filename, size: zipBlob.size };
}

/**
 * 프로젝트 하나를 ZIP으로 묶어 다운로드. (system / handoff)
 * concept 모드는 exportConceptPrompt 로 분기됨.
 * @param {object} params
 * @param {object} params.project - Project 엔티티
 * @param {object} params.analysis - AnalysisLayers (layers 직접 접근 가능한 형태)
 * @param {array}  params.references - 전체 store references (사용되는 것만 ZIP에 포함)
 * @returns {Promise<{ filename: string, size: number }>}
 */
export async function exportProjectAsZip({ project, analysis, references }) {
  // concept 모드: ZIP 대신 .md 단일 파일
  if (project?.mode === 'concept') {
    return exportConceptPrompt({ project, analysis });
  }
  // handoff 모드: 5 layer 상세 + 프레임워크 config 포함 번들
  if (project?.mode === 'handoff') {
    return exportHandoffBundle({ project, analysis, references });
  }

  const zip = new JSZip();
  const universal = buildUniversalJson({ project, analysis, references });

  // 1) muse.json (universal tokens)
  zip.file('muse.json', JSON.stringify(universal, null, 2));

  // 2) standalone visual-direction.md
  const md = analysis?.visualDirection?.markdown;
  if (md) {
    zip.file('visual-direction.md', md);
  }

  // 3) README for AI tools
  zip.file('README.md', buildReadme(project, references));

  // 3.5) ai-paste-block.md — 외부 AI 도구 paste 용 (플랫폼 중립) (모든 mode 공통)
  zip.file('ai-paste-block.md', buildAiPasteBlock({ project, analysis, references }));

  // 4) references/ — 사용 이미지만 바이너리로 (첨부 순번 prefix: 01-ref-XXX)
  const projectRefs = (project.referenceIds || [])
    .map((id) => (references || []).find((r) => r.id === id))
    .filter(Boolean);
  const refsFolder = zip.folder('references');

  await Promise.all(
    projectRefs.map(async (ref, i) => {
      const prefix = String(i + 1).padStart(2, '0');
      const filename = `${prefix}-${ref.id}${inferImageExt(ref.thumbnailUrl)}`;
      try {
        const res = await fetch(ref.thumbnailUrl);
        if (!res.ok) throw new Error(`status ${res.status}`);
        const blob = await res.blob();
        refsFolder.file(filename, blob);
      } catch (e) {
        refsFolder.file(
          `${prefix}-${ref.id}.error.txt`,
          `Failed to include image: ${e?.message || String(e)}`,
        );
      }
    }),
  );

  // 5) Generate & download
  const blob = await zip.generateAsync({ type: 'blob' });
  const slug = slugify(project.name);
  const date = new Date().toISOString().slice(0, 10);
  const filename = `muse-${slug}-${date}.zip`;

  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);

  return { filename, size: blob.size };
}

/**
 * handoff 모드 전용 번들. tokens 으로부터 framework config 를 결정론적으로 생성.
 *
 * ZIP 구조:
 *   muse-handoff-{slug}.zip
 *   ├── tokens.dtcg.json                   # 진실의 원천
 *   ├── DESIGN_SYSTEM.md                   # 5 layer 한글 상세 + 전환 가이드
 *   ├── .cursorrules                        # AI 코딩 도구 컨텍스트
 *   ├── README.md                           # 사용 가이드
 *   ├── frameworks/
 *   │   ├── tailwind.config.js
 *   │   ├── mui-theme.js
 *   │   └── tokens.css
 *   └── references/
 *       └── {ref-id}.{ext}
 */
export async function exportHandoffBundle({ project, analysis, references }) {
  const zip = new JSZip();
  const tokens = {
    color: analysis?.color || [],
    typography: analysis?.typography || [],
    layout: analysis?.layout || [],
    gradient: analysis?.gradient || [],
  };
  const visualDirection = analysis?.visualDirection || { markdown: '', tags: {} };
  const layerDetails = analysis?.layerDetails || null;

  // 1) DTCG (source of truth)
  zip.file('tokens.dtcg.json', JSON.stringify(buildDtcgTokens(tokens), null, 2));

  // 2) Frameworks
  const fw = zip.folder('frameworks');
  fw.file('tailwind.config.js', buildTailwindConfig(tokens));
  fw.file('mui-theme.js', buildMuiTheme(tokens));
  fw.file('tokens.css', buildCssVariables(tokens));

  // 3) DESIGN_SYSTEM.md (5 layer 상세 + 전환 가이드 + 정확한 ref 파일명 매칭표)
  zip.file('DESIGN_SYSTEM.md', buildDesignSystemMd({ project, tokens, visualDirection, layerDetails, references }));

  // 4) .cursorrules — references 포함하여 매칭 표 박힘
  zip.file('.cursorrules', buildCursorRules({ project, tokens, layerDetails, references }));

  // 5) README — 짧은 사용 가이드 + 매칭 표
  zip.file('README.md', buildHandoffReadme(project, references));

  // 5.5) ai-paste-block.md — 외부 AI 도구 paste 용 (플랫폼 중립)
  zip.file('ai-paste-block.md', buildAiPasteBlock({ project, analysis, references }));

  // 6) references/ — 사용 이미지 바이너리 (첨부 순번 prefix, paste block 매칭 단서와 일치)
  const projectRefs = (project.referenceIds || [])
    .map((id) => (references || []).find((r) => r.id === id))
    .filter(Boolean);
  const refsFolder = zip.folder('references');
  await Promise.all(projectRefs.map(async (ref, i) => {
    const prefix = String(i + 1).padStart(2, '0');
    const filename = `${prefix}-${ref.id}${inferImageExt(ref.thumbnailUrl)}`;
    try {
      const res = await fetch(ref.thumbnailUrl);
      if (!res.ok) throw new Error(`status ${res.status}`);
      const blob = await res.blob();
      refsFolder.file(filename, blob);
    } catch (e) {
      refsFolder.file(`${prefix}-${ref.id}.error.txt`, `Failed to include image: ${e?.message || String(e)}`);
    }
  }));

  // 7) Generate & download
  const blob = await zip.generateAsync({ type: 'blob' });
  const slug = slugify(project.name);
  const date = new Date().toISOString().slice(0, 10);
  const filename = `muse-handoff-${slug}-${date}.zip`;

  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);

  return { filename, size: blob.size };
}

function buildHandoffReadme(project, references) {
  const attachmentTable = buildAttachmentTable(project, references);
  return `# ${project?.name || 'Handoff Bundle'}

_Generated by MUSE on ${new Date().toISOString().slice(0, 10)} (mode: handoff)_

## Reference Images (외부 AI 에 첨부할 정확한 파일명)

${attachmentTable}

## 파일 구성

| 파일 | 용도 |
|------|------|
| \`tokens.dtcg.json\` | DTCG 표준 토큰 (진실의 원천) |
| \`DESIGN_SYSTEM.md\` | 5 layer 한글 상세 + 프레임워크 전환 가이드 |
| \`ai-paste-block.md\` | 외부 AI paste 용 (플랫폼 중립) |
| \`.cursorrules\` | Cursor / Claude Code 컨텍스트 |
| \`frameworks/tailwind.config.js\` | Tailwind 변환 |
| \`frameworks/mui-theme.js\` | MUI v7 theme |
| \`frameworks/tokens.css\` | 순수 CSS variables |
| 각 reference 이미지 | 위 매칭 표 참조 |

## 빠른 시작

### Tailwind
\`\`\`bash
cp frameworks/tailwind.config.js ./tailwind.config.js
\`\`\`

### MUI v7
\`\`\`js
import theme from './frameworks/mui-theme.js';
<ThemeProvider theme={theme}>{children}</ThemeProvider>
\`\`\`

### Pure CSS
\`\`\`css
@import './frameworks/tokens.css';
.btn { background: var(--color-primary); }
\`\`\`

### AI 코딩 도구
프로젝트 루트에 \`.cursorrules\` 복사 → Cursor / Claude Code 가 자동 인지.

## 전체 가이드
\`DESIGN_SYSTEM.md\` 참조.
`;
}

/**
 * muse.json만 다운로드 (이미지 제외 가벼운 경로).
 */
export function downloadUniversalJson({ project, analysis, references }) {
  const universal = buildUniversalJson({ project, analysis, references });
  const slug = slugify(project.name);
  const blob = new Blob([JSON.stringify(universal, null, 2)], {
    type: 'application/json;charset=utf-8',
  });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `muse-${slug}.json`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
